export type * from "./types";

export { default, Nav } from "./view";

export {
  NAV_ACTION_DISMISS_TRANSITION,
  NAV_BACKDROP_TRANSITION,
  NAV_BUTTON_TRANSITION,
  NAV_CARD_COLLAPSE_TRANSITION,
  NAV_CARD_EXPAND_TRANSITION,
  NAV_CARD_HEIGHT_CLOSE_TRANSITION,
  NAV_CARD_HEIGHT_OPEN_TRANSITION,
  NAV_CARD_SPRING,
  NAV_CARD_TRANSITION,
  NAV_COMPACT_RESTORE_DURATION_MS,
  NAV_COMPACT_STACK_ENTER_TRANSITION,
  NAV_COMPACT_STACK_EXIT_TRANSITION,
  NAV_COMPOSITOR_STYLE,
  NAV_FADE_TRANSITION,
  NAV_HEADER_SWAP_TRANSITION,
  NAV_MEDIA_VOLUME_FILL_TRANSITION,
  NAV_MEDIA_VOLUME_THUMB_POSITION_TRANSITION,
  NAV_MICRO_TRANSITION,
  NAV_REDUCED_MOTION_TRANSITION,
  NAV_RESULTS_EXIT_TRANSITION,
  NAV_RESULTS_STAGGER_DELAY,
  NAV_RESULTS_TRANSITION,
  NAV_SCRUBBER_TOOLTIP_SPRING,
  NAV_SCRUBBER_TOOLTIP_TRANSITION,
  NAV_SKELETON_PULSE_CLASS,
  NAV_STACK_TRANSITION,
  NAV_SURFACE_BODY_ENTER_TRANSITION,
  NAV_SURFACE_BODY_EXIT_TRANSITION,
  NAV_SURFACE_BODY_STEP_TRANSITION,
  NAV_SURFACE_CHOREOGRAPHY_TIMINGS,
  NAV_SURFACE_DRAG,
  NAV_SURFACE_DRAG_CONSTRAINTS,
  NAV_SURFACE_DRAG_ELASTIC,
  NAV_SURFACE_DRAG_INTERPOLATION,
  NAV_SURFACE_DRAG_THRESHOLDS,
  NAV_SURFACE_EXTENSIONS_ENTER_TRANSITION,
  NAV_SURFACE_EXTENSIONS_EXIT_TRANSITION,
  NAV_SURFACE_HEADER_REVEAL_DELAY_MS,
  NAV_SURFACE_RESIZE_TRANSITION,
  NAV_SURFACE_TRANSITION,
  NAV_TAP_SCALE,
  getNavActionStaggerTransition,
  getNavBackdropTransition,
  getNavCardContentAnimateProps,
  getNavCardDelay,
  getNavDescriptionVariants,
  getNavItemAnimateValues,
  getNavItemTransition,
  getNavMediaVolumeFillTransition,
  getNavMediaVolumeThumbAnimateProps,
  getNavMediaVolumeThumbPositionTransition,
  getNavScrollProgressStyle,
  getNavStackAnimateProps,
  getPrefersReducedMotion,
  navActionDismissVariants,
  navActionVariants,
  navBackdropVariants,
  navBadgeVariants,
  navBreadcrumbsVariants,
  navCommandBarSwapVariants,
  navFadeVariants,
  navHeaderRestoreVariants,
  navHeaderSwapVariants,
  navHudVariants,
  navIconVariants,
  navListItemVariants,
  navMediaVolumeThumbVariants,
  navScrubberTooltipVariants,
  navSoundwaveBarVariants,
  navSurfaceBodyVariants,
  navSurfaceControlsActionVariants,
  navSurfaceControlsBackVariants,
  navSurfaceControlsCloseVariants,
  navSurfaceControlsContainerVariants,
  navSurfaceControlsVariants,
  navSurfaceDragTransformTemplate,
  navSurfaceExtensionsVariants,
  slideFadeVariants,
  staggerItemVariants,
  textCrossfadeVariants,
} from "./motion";

export {
  NAV_ACTION_STYLES,
  NAV_ATTENTION_KIND,
  NAV_ATTENTION_PRIORITY,
  NAV_ATTENTION_PRIORITY_OFFSET_MAX,
  NAV_COLLAPSE_TO_COMPACT_DELAY_MS,
  NAV_HUD_PRIORITY,
  NAV_HUD_RENDER_MODE,
  NAV_HUD_VARIANT,
  NAV_SURFACE_FLOW_STATUS,
  NAV_SURFACE_PHASE,
  NAV_SURFACE_RENDER_MODE,
  NAVIGATION_CONTINUITY_EVENTS,
  NAVIGATION_DIAGNOSTIC_EVENTS,
  NAVIGATION_EVENTS,
  NAVIGATION_LIFECYCLE,
  NAVIGATION_OPERATION_EVENTS,
  NAVIGATION_OPERATION_STATUS,
  NAVIGATION_SURFACE_RETURN_MAX_ENTRIES,
  NAVIGATION_TRANSACTION_STATUS,
  SEMANTIC_SURFACE_CLASSES,
} from "./constants";

export {
  getNavActionClass,
  isEqualRoutePath,
  isSameItem,
  isSameNavItem,
  isSamePath,
  isValidComponentType,
} from "./utils";

export {
  NavMediaControls,
  NavMediaScrubber,
  NavSoundwave,
  formatMediaTime,
} from "./media";

export {
  NavCardHeader,
  NavDescription,
  NavIcon,
  NavTitle,
  resolveNavHeaderKey,
} from "./cards";

export {
  BreadcrumbProvider,
  NavBreadcrumbsCard,
  resolveRouteBreadcrumbs,
  useBreadcrumbActions,
  useBreadcrumbOverrides,
  useNavBreadcrumbs,
  useRegisterBreadcrumbOverride,
} from "./breadcrumbs";

export {
  areHudDefinitionsEqual,
  createHudDefinition,
  createNavigationOperationHud,
  isHudDescriptor,
  resolveActiveHud,
  upsertHudEntry,
} from "./hud";

export {
  NavSurfaceAction,
  NavSurfaceExtension,
  NavSurfaceExtensionsBar,
  SurfaceDimensionsContext,
  SurfaceExtensionsContext,
  SurfaceExtensionsProvider,
  SurfaceHeaderActionContext,
  applySurfaceToNavItem,
  createInlineSurfaceEntry,
  createPendingSurfaceScheduler,
  createSurfaceEntryDefinition,
  createSurfaceFlowDefinition,
  createSurfaceFlowSession,
  createSurfaceReturnHandshake,
  isSurfaceDescriptor,
  normalizeSurfaceExtension,
  resolveActiveStepDefinition,
  resolveSurfaceAction,
  updateSurfaceFlowSession,
  useIsSurfaceExtensionsVisible,
  useSurfaceAction,
  useSurfaceDimensions,
  useSurfaceExtensions,
  useSurfaceFlow,
  useSurfaceHeader,
  useSurfaceId,
} from "./surface";

export {
  ErrorAction,
  ErrorActions,
  GuardAction,
  GuardActions,
  applyStatusOverlay,
  clearLastKnownAccount,
  createErrorStatus,
  createGuardStatus,
  getStatusTheme,
  readLastKnownAccount,
  resolveAuthIcon,
  resolveAuthStatusDetails,
  saveLastKnownAccount,
  useNavigationStatus,
} from "./status";

export {
  createNavigationContinuityEntry,
  createNavigationContinuityState,
  createNavigationReturnHandoff,
  createNavigationTopology,
  createNavigationTransaction,
  createNavigationTransactionState,
  getNavigationLocationKey,
  navigationContinuityReducer,
  navigationTransactionReducer,
  resolveNavigationContinuityEntry,
  resolveNavigationReturnHandoffs,
  resolveNavigationRoutePolicy,
  resolveNavigationTopologyPath,
  useNavigationContinuity,
  useNavigationTransactions,
  useRoutePrefetch,
} from "./routing";

export {
  canUseBottomLock,
  focusNavigationElement,
  getNavigationFocusableElements,
  shouldRestoreNavigationFocus,
} from "./behavior";

export {
  NavHeightSpacer,
  NavHud,
  NavSurfaceControls,
  NavSurfaceHeader,
  NavSurfaceHeaderButton,
  NavSurfaceShell,
  NavigationProvider,
  checkGuards,
  clearNavigationGuards,
  createNavigationMachineState,
  getNavigationGuardCount,
  navigationStateReducer,
  registerGuard,
  resolveNavigationAttention,
  useNavContextActions,
  useNavDimensions,
  useNavHeight,
  useNavHud,
  useNavigation,
  useNavigationActions,
  useNavigationContext,
  useNavigationContinuityState,
  useNavigationGuard,
  useNavigationOperations,
  useNavigationRuntimeHealth,
  useNavigationSelector,
  useNavigationState,
  useSurfaceReturn,
} from "./provider";

export {
  clearNavigationDiagnostics,
  createNavigationDiagnosticStore,
  createNavigationInspectorSnapshot,
  createNavigationOperation,
  createNavigationOperationState,
  getNavigationDiagnostics,
  getNavigationInspectorSnapshot,
  navigationOperationReducer,
  resolveActiveNavigationOperation,
} from "./runtime";

export {
  defineBreadcrumb,
  defineHud,
  defineNavAction,
  defineStepSurface,
  defineSurface,
  useHud,
  useNav,
  useNavBanner,
  useSurface,
  useSurfaceStep,
} from "./builder";
