export const ENV_CONFIG = {
  requiredEnvVars: ['NEXT_PUBLIC_API_URL'],

  requiredServerEnvVars: ['MONGODB_URI', 'MONGODB_DB'],

  firebaseEnvVars: [
    'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
    'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
    'NEXT_PUBLIC_FIREBASE_DATABASE_URL',
    'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
    'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
    'NEXT_PUBLIC_FIREBASE_API_KEY',
    'NEXT_PUBLIC_FIREBASE_APP_ID',
  ],
}
